### ISSUE TITLE
Does not work with iOS or Safari Desktop

### ISSUE THREAD

**Issue by ngokevin** [maxkrieger/aframe-draw-component#2]
Getting CORS errors. Is there a workaround?

I tried sending the data URL to an `<img>` with `crossorigin`, and then reading from that, but that didn't work.

**Comment by mayognaise** [comment]
:sob:

**Comment by ngokevin** [comment]
http://jeromeetienne.github.io/threex.proceduralcity/examples/demo.html seems to be able to provide a canvas as a texture in Safari.

**Comment by maxkrieger** [comment]
Yeah me and @mayognaise were discussing this problem yesterday. I'll see if I can find a solution in the coming weeks. If anyone finds any more insight on this let me know.

**Comment by maxkrieger** [comment]
I believe I've solved this with `1.3.0` by piping directly from canvas to texture. Let me know if it works now! @mayognaise @ngokevin 

https://github.com/maxkrieger/aframe-draw-component/issues/3

**Comment by amicoleo** [comment]
Hi, this works for me on Safari Desktop and iOS Safari.

**Comment by ngokevin** [comment]
Woot!
